name: Deployment

env:
  DEPLOY_PACKAGE_NAME_FILE: "${{ github.sha }}.zip"
  DEPLOY_PACKAGE_NAME: "${{ github.sha }}"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: create file
        run: sudo touch abc.text

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build

      - name: Create zip deployment package
        run: zip -r angular-app ./dist/test-ci-cd-angular/browser

      - name: Check
        run: ls

      - name: Set Up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.LIGHTSAIL_KEY}}

      - name: SCP file to remote server
        run: touch key.pem && echo ${{secrets.LIGHTSAIL_KEY}} > key.pem

      - name: SCP file to remote server
        run: scp -i ${{env.SSH_AUTH_SOCK}} angular-app.zip ubuntu@13.214.22.14:/var/www/

#      - name: Copy File via SSH Password
#        uses: appleboy/scp-action@master
#        with:
#          HOST: ${{  secrets.LIGHTSAIL_IP}}
#          USERNAME: ${{ secrets.LIGHTSAIL_USERNAME}}
#          KEY: ${{ secrets.LIGHTSAIL_KEY }}
#          source: angular-app.zip
#          target: "/var/www/"
#          strip_components: 1
#
#      - name: Extract File in Remote Sever
#        uses: appleboy/ssh-action@v0.1.7
#        with:
#          HOST: ${{  secrets.LIGHTSAIL_IP}}
#          USERNAME: ${{ secrets.LIGHTSAIL_USERNAME}}
#          KEY: ${{ secrets.LIGHTSAIL_KEY }}
#          source: angular-app.zip
#          script:
#            sudo apt-get install zip unzip && cd /var/www/ && unzip angular-app.zip && ls
