name: Deployment

env:
  APP_NAME: "test-ci-cd-angular"
  PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
  HOST_NAME: ${{secrets.LIGHTSAIL_IP}}
  USER_NAME: ${{secrets.LIGHTSAIL_USERNAME}}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Angular
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: ng build

      - name: Create zip deployment package
        run: |
          cd ./dist/${{env.APP_NAME}}/browser/
          zip -r ${{env.APP_NAME}} .

      - name: Check
        run: cd ./dist/${{env.APP_NAME}}/browser/ && ls

      - name: create file
        run: |
          echo "${{env.PRIVATE_KEY}} ${{env.USER_NAME}} ${{env.HOST_NAME}}"
          echo "${{env.PRIVATE_KEY}}" > private_key && chmod 600 private_key
          scp -o StrictHostKeyChecking=no -i private_key ./dist/test-ci-cd-angular/browser/angular-app.zip ${{env.USER_NAME}}@${{env.HOST_NAME}}:/var/www/
          ssh -o StrictHostKeyChecking=no -i private_key ${{env.USER_NAME}}@${{env.HOST_NAME}} '
            cd /var/www/
            sudo unzip -o angular-app.zip
          '
